package net.commoble.structurebuddy.api;

import java.util.List;

import org.jspecify.annotations.Nullable;

import com.mojang.serialization.Codec;
import com.mojang.serialization.MapCodec;

import net.commoble.structurebuddy.api.util.CodecBuddy;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Holder;
import net.minecraft.resources.RegistryFileCodec;
import net.minecraft.world.level.LevelReader;
import net.minecraft.world.level.ServerLevelAccessor;
import net.minecraft.world.level.levelgen.structure.templatesystem.StructurePlaceSettings;
import net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate;
import net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.StructureBlockInfo;
import net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.StructureEntityInfo;

/// Analogue of StructureProcessor for dynamic jigsaw structures.
/// 
/// DynamicProcessors provide read access to jigsaw data while processing blocks/entities.
/// This data will be a copy of whatever data the jigsaw assembler had at the time the piece was selected.
/// 
/// Other than that, methods are similar to StructureProcessor;
/// using input block/entity data from a StructureTemplate or similar phenomena,
/// the data is fed into a list of DynamicStructureProcesors,
/// each of which runs on the previous processor's output
/// until the list is exhausted (in which case the final result is used for placement into the world)
/// or a null is returned (in which case the input is discarded and nothing is placed).
/// 
/// DynamicProcessor types can be registered to {@link StructureBuddyRegistries#DYNAMIC_PROCESSOR_TYPE}
/// and dynamic processor lists can be defined in data files in the structurebuddy/dynamic_processor_list datapack registry.
/// 
public interface DynamicProcessor
{
	/// ```json
	/// {
	/// 	"type": "modid:some_registered_type",
	/// 	// additional fields as specified by registered type
	/// }
	/// ```
	public static final Codec<DynamicProcessor> SINGLE_CODEC = CodecBuddy.dispatch(StructureBuddyRegistries.DYNAMIC_PROCESSOR_TYPE, DynamicProcessor::codec);
	
	/// ```json
	/// [
	/// 	{
	/// 		"type": "modid:some_registered_type",
	/// 		// additional fields
	/// 	}
	/// ]
	/// ```
	/// 
	/// vanilla-like object format is also supported:
	/// ```json
	/// {
	/// 	"processors": [
	/// 		{
	/// 			"type": "modid:some_registered_type",
	/// 			// additional fields
	/// 		}
	/// 	]
	/// }
	/// ```
	public static final Codec<List<DynamicProcessor>> DIRECT_LIST_CODEC = Codec.withAlternative(
		SINGLE_CODEC.listOf().fieldOf("processors").codec(),
		SINGLE_CODEC.listOf());
	
	/// Same format as {@link DIRECT_LIST_CODEC}, will serialize as file id if tthis is a registered processor list
	public static final Codec<Holder<List<DynamicProcessor>>> LIST_HOLDER_CODEC = RegistryFileCodec.create(StructureBuddyRegistries.DYNAMIC_PROCESSOR_LIST, DIRECT_LIST_CODEC);
	
	/// {@return registered MapCodec to serialize this processor with}
	public abstract MapCodec<? extends DynamicProcessor> codec();

	/// Modifies some block generated by a structure template or similar phenomena.
	/// @param level LevelReader from which information can be read to determine how to process the block
	/// @param targetPosition BlockPos whose semantics depends on context but usually indicates the minimal corner of the structurepiece being generated
	/// @param referencePos BlockPos whose semantics depends on context but usually indicates the center of the structure piece
	/// @param originalBlockInfo StructureBlockInfo originally produced by a StructureTemplate or similar phenomena, before any modifications have been applied
	/// @param processedBlockInfo StructureBlockInfo consisting of the originalBlockInfo modified by any structure processors that have run before this one
	/// @param settings StructurePlaceSettings of the structure being placed
	/// @param template StructureTemplate, if one is being processed
	/// @param jigsawData JigsawPieceDataReader containing additional parameters defined by pieces selected during jigsaw assembly
	/// @return StructureBlockInfo to place in the world, or null if no block should be placed into the world
	public default @Nullable StructureBlockInfo process(
		LevelReader level,
		BlockPos targetPosition,
		BlockPos referencePos,
		StructureBlockInfo originalBlockInfo,
		StructureBlockInfo processedBlockInfo,
		StructurePlaceSettings settings,
		@Nullable StructureTemplate template,
		JigsawPieceDataReader jigsawData)
	{
		return processedBlockInfo; // noop by default
	}
	
	/// Postprocesses the list of blocks to generate after structure processors finish making per-block modifications.
	/// @param level ServerLevelAccessor to get data from during world generation.
	/// Be aware that structure generation is off-thread and so only immutable data should be read (and no data should be written to the serverlevel)
	/// @param position BlockPos whose semantics depends on context but usually indicates the minimal corner of the structurepiece being generated
	/// @param referencePos BlockPos whose semantics depends on context but usually indicates the center of the structure piece
	/// @param originalBlockInfoList List of StructureBlockInfos prior to any processor modification
	/// @param processedBlockInfoList List of StructureBlockInfos returned by the previous processor
	/// @param settings StructurePlaceSettings for the structure being placed
	/// @param jigsawData JigsawPieceDataReader containing additional parameters defined by pieces selected during jigsaw assembly
	/// @return List of StructureBlockInfos to place in the world
	public default List<StructureBlockInfo> finalizeProcessing(
		ServerLevelAccessor level,
		BlockPos position,
		BlockPos referencePos,
		List<StructureBlockInfo> originalBlockInfoList,
		List<StructureBlockInfo> processedBlockInfoList,
		StructurePlaceSettings settings,
		JigsawPieceDataReader jigsawData)
	{
		return processedBlockInfoList; // noop by default
	}

	/// Processes some entity being placed by a StructureTemplate or similar phenemona
	/// @param world LevelReader from which information can be read from to determine how to process the enttity
	/// @param seedPos BlockPos whose semantics depends on context but usually indicates the minimal corner of the structurepiece being generated
	/// @param rawEntityInfo StructureEntityInfo produced by StructureTemplate or similar
	/// @param entityInfo StructureEntityInfo consisting of original entity info + modifications by prior processors
	/// @param placementSettings StructurePlaceSettings of structure being placed
	/// @param template StructureTemplate being placed, if any
	/// @param jigsawData JigsawPieceDataReader containing additional parameters defined by pieces selected during jigsaw assembly
	/// @return StructureEntityInfo to place in the world, or null if no entity should be placed
	public default @Nullable StructureEntityInfo processEntity(
		LevelReader world,
		BlockPos seedPos,
		StructureEntityInfo rawEntityInfo,
		StructureEntityInfo entityInfo,
		StructurePlaceSettings placementSettings,
		@Nullable StructureTemplate template,
		JigsawPieceDataReader jigsawData)
	{
		return entityInfo; // noop by default
	}
}
